/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef ECS_SHAPES_BAKE_CONFIG_H
#define ECS_SHAPES_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <reflecs>
#include <bake.util>
#include <reflecs.components.transform>
#include <reflecs.components.physics>
#include <rti.connext.systems.shapes>

/* Headers of private dependencies */
#ifdef ECS_SHAPES_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if ECS_SHAPES_IMPL && defined _MSC_VER
#define ECS_SHAPES_EXPORT __declspec(dllexport)
#elif ECS_SHAPES_IMPL
#define ECS_SHAPES_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
#define ECS_SHAPES_EXPORT __declspec(dllimport)
#else
#define ECS_SHAPES_EXPORT
#endif

#endif

